export enum ADMIN_PERMISSIONS {
  // manage users
  CREATE_USER = "CREATE_USER",
  DELETE_USER = "DELETE_USER",
  ENROLL_USERS_IN_COURSE = "ENROLL_USERS_IN_COURSE",
  ADD_TEACHERS_IN_COURSE = "ADD_TEACHERS_IN_COURSE",

  // manage permissions
  ADD_PERMISSIONS_TO_USER = "ADD_PERMISSIONS_TO_USER",
  REMOVE_PERMISSIONS_FROM_USER = "REMOVE_PERMISSIONS_FROM_USER",

  // manage permissions groups
  CREATE_PERMISSIONS_GROUP = "CREATE_PERMISSIONS_GROUP",
  DELETE_PERMISSIONS_GROUP = "DELETE_PERMISSIONS_GROUP",
  EDIT_PERMISSIONS_GROUP = "EDIT_PERMISSIONS_GROUP",

  // manage course materials
  EDIT_COURSE_MATERIALS = "EDIT_COURSE_MATERIALS",

  // manage courses
  CREATE_COURSE = "CREATE_COURSE",
  CREATE_BASE_COURSE = "CREATE_BASE_COURSE",
  DELETE_COURSE = "DELETE_COURSE",
  EDIT_COURSE = "EDIT_COURSE",
  ADD_PREREQUISITE_COURSES_TO_COURSE = "ADD_PREREQUISITE_COURSES_TO_COURSE",
  REMOVE_PREREQUISITE_COURSES_TO_COURSE = "REMOVE_PREREQUISITE_COURSES_TO_COURSE",
  ADD_PREREQUISITE_COURSE_GROUPS_TO_COURSE = "ADD_PREREQUISITE_COURSE_GROUPS_TO_COURSE",
  REMOVE_PREREQUISITE_COURSE_GROUPS_TO_COURSE = "REMOVE_PREREQUISITE_COURSE_GROUPS_TO_COURSE",

  // manage course groups
  CREATE_COURSE_GROUP = "CREATE_COURSE_GROUP",
  DELETE_COURSE_GROUP = "DELETE_COURSE_GROUP",
  EDIT_COURSE_GROUP = "EDIT_COURSE_GROUP",
}
