enum ADMIN_PERMISSIONS {
  // manage users
  CREATE_USER = 'CREATE_USER',
  DELETE_USER = 'DELETE_USER',

  // manage permissions
  ADD_PERMISSIONS_TO_USER = 'ADD_PERMISSIONS_TO_USER',
  REMOVE_PERMISSIONS_FROM_USER = 'REMOVE_PERMISSIONS_FROM_USER',

  // manage permissions groups
  CREATE_PERMISSIONS_GROUP = 'CREATE_PERMISSIONS_GROUP',
  DELETE_PERMISSIONS_GROUP = 'DELETE_PERMISSIONS_GROUP',
  EDIT_PERMISSIONS_GROUP = 'EDIT_PERMISSIONS_GROUP',

  // manage course materials
  EDIT_COURSE_MATERIALS = 'EDIT_COURSE_MATERIALS',
}

export default ADMIN_PERMISSIONS;
